repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    stages:
    - commit
    - push
    hooks:
    -   id: flake8
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict