repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: ["-l 79", "lumapps"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    stages:
    - commit
    - push
    hooks:
    -   id: flake8
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: pytest
        name: Check pytest unit tests pass
        entry: poetry run pytest
        pass_filenames: false
        language: system
        types: [python]
    -   id: mypy
        name: Check mypy static types match
        entry: poetry run mypy . --ignore-missing-imports
        pass_filenames: false
        language: system
        types: [python]