site_name: LumApps SDK
site_description: "LumApps sdk documentation"
site_url: "https://lumapps.github.io/lumapps-sdk"
repo_url: "https://github.com/lumapps/lumapps-sdk"
repo_name: "lumapps/lumapps-sdk"

theme:
  name: "material"

nav:
    - Overview: index.md
    - Reference:
      - Api Client: api_client.md
      - Widgets: widgets.md
      - Medias: medias.
    - Copyright and license: LICENSE.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - lumapps