name: Pypi publish 📦

on:
  release:
    types: [published]

jobs:

  Package:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python 3.7 🐍
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - uses: actions/cache@v1
        name: Cache Poetry deps
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: pypi-${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            pypi-${{ runner.os }}-poetry-
              
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.cache/poetry/virtualenvs
      
      - name: Install Dependencies
        run: poetry install -v --no-interaction
        if: steps.cache.outputs.cache-hit != 'true'

      - name: 📦 Build Python package and publish to PyPI 📦
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
