name: Pypi 📦

on: push

jobs:

  Package:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python 3.7 🐍
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Build library
        run: |
          python setup.py sdist bdist_wheel
          
      - name: Publish to PyPI 📦
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        
      - name: Notify slack
        if: startsWith(github.event.ref, 'refs/tags')
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          # GLBSCC25D => Lab Monitoring channel
          # C45PD5QSE => Lab channel
          args: '{\"channel\":\"C45PD5QSE\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"The LumApps SDK ${{ steps.get_version.outputs.VERSION }} is available\n \t`pip install lumapps-sdk`\"}}]}'
          